spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://zipkin:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
  rabbitmq:
#    host: 127.0.0.1
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  aop:
    proxy-target-class: true
    auto: true

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
#      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.userservice.client: DEBUG
    io.micrometer: DEBUG
    org.springframework.boot.actuate: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

#token:
#  expiration_time: 86400000
#  secret: thisisaverysecurekeywithatleast32characterslongthisisaverysecurekeywithatleast32characterslong

greeting:
  message: Welcome to the Simple E-Commerce.

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
#      endpoint: http://localhost:9411/api/v2/spans
      endpoint: http://zipkin:9411/api/v2/spans


  endpoints:
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,prometheus,metrics
  metrics:
    distribution:
      percentiles-histogram:
        users.status: true
        users.welcome: true

